services:
  osm-extractor-workflow-start:
    container_name: osm-extractor-workflow-start
    env_file:
      - path: .env.development.local
        required: true
    environment:
      TEMPORAL_URL: host.docker.internal:7233
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: osm-extractor:local
    build:
      context: .
    labels:
      - 'app=osm-extractor-workflow-start'
    command: ['/app/osm-extractor-workflow', 'create']
  osm-extractor-worker:
    container_name: osm-extractor-worker
    env_file:
      - path: .env.development.local
        required: true
    environment:
      TEMPORAL_URL: host.docker.internal:7233
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: osm-extractor:local
    build:
      context: .
    labels:
      - 'app=osm-extractor-worker'
    volumes:
      - ./volumes/input:/mnt/input 
      - ./volumes/output:/mnt/output
    command: ['/app/osm-extractor-workflow', 'worker']
    depends_on:
      osm-extractor-workflow-start:
        condition: service_completed_successfully
  osm-extractor-workflow-resume:
    profiles: ['resume']
    container_name: osm-extractor-workflow-resume
    env_file:
      - path: .env.development.local
        required: true
    environment:
      TEMPORAL_URL: host.docker.internal:7233
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: osm-extractor:local
    build:
      context: .
    labels:
      - 'app=osm-extractor-workflow-resume'
    command: ['./osm-extractor-workflow', 'resume']
  osm-extractor-workflow-pause:
    profiles: ['pause']
    container_name: osm-extractor-workflow-pause
    env_file:
      - path: .env.development.local
        required: true
    environment:
      TEMPORAL_URL: host.docker.internal:7233
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: osm-extractor:local
    build:
      context: .
    labels:
      - 'app=osm-extractor-workflow-pause'
    command: ['./osm-extractor-workflow', 'pause']