services:
  osm-extractor-worker:
    container_name: osm-extractor-worker
    env_file:
      - path: .env.development.local
        required: true
    environment:
      TEMPORAL_URL: host.docker.internal:7233
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: osm-extractor:local
    build:
      context: .
    labels:
      - 'app=osm-extractor-worker'
    volumes:
      - ./volumes/input:/mnt/input 
      - ./volumes/output:/mnt/output
    command: ['/app/osm-extractor-workflow', 'worker']